### ISSUE TITLE
Social cards for ALL ar5iv articles

### ISSUE THREAD

**Issue by crazy4pi314** [dginev/ar5iv#112]
Hi! 

I have been sharing a lot of ar5iv links lately, and it would be nice to have the social card configured to show the paper title and abstract preview like arXiv does:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/6486256/158650880-7d8c8837-ae15-4173-a4fc-cdb32aa71037.png">

(Each webservice can do subtly different things, just using the [twitter validator](https://cards-dev.twitter.com/validator) for an example here).

**Comment by dginev** [comment]
Hi @crazy4pi314 !

ar5iv actually already has these cards enabled and you will see them on some articles, e.g. [this tweet](https://twitter.com/rasbt/status/1489612345227845634)

I was also frustrated that they don't work on all articles yet, and it appears that the reason is the twitter-imposed [size maximum of 2MB](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/troubleshooting-cards) for the pages they allow creating cards for.

I wish there was a way to circumvent that limit... The main reason why the ar5iv pages are this large is the inclusion of extended MathML for mathematical syntax, as well as adding fine-grained id attributes to most elements.

Let me know if you have any ideas how we can interoperate with twitter to avoid the limit, I'm certainly interested in enabling cards for all articles.

**Comment by dginev** [comment]
Well, three things seem to have happened:
 - the twitter card validator is no longer functional, for obvious reasons
 - some minor downsizing to the articles took place in the latest update, so more of them will have cards
 - ar5iv is now en route to being retired, as arXiv is taking the HTML to the official pages. 

So I will close here for now, and defer the question to arXiv's team.
