### ISSUE TITLE
[feature request] Display page number

### ISSUE THREAD

**Issue by a234** [dginev/ar5iv#152]
Some people refer to arXiv papers by page numbers, e.g. "arXiv 1010.1010, pg. 10". It may be beneficial if page numbers can be visible on ar5iv.

**Comment by dginev** [comment]
I am tempted to actually give a quick apology here and reject the request - at least in the mid-term horizon of ar5iv.

The problem is somewhat fundamental. In our process to convert the latex sources into HTML5, the page information is no longer computer, as there are no pages to speak of in the final web documents.

So this will remain a limitation for the foreseeable future, unless we find some clever way to re-attribute page references to heading/object references. Some examples would help, but I really doubt we can solve this in a reasonable way.
