### ISSUE TITLE
Confuse: How do you prevent us from accessing papers from 2205 onwards？

### ISSUE THREAD

**Issue by CreatorZZY** [dginev/ar5iv#168]
Example: [https://ar5iv.org/abs/2207.13987](https://ar5iv.org/abs/2207.13987)
I can find anything about restriction in the project src.
How did you do that?

**Comment by dginev** [comment]
Hi @CreatorZZY . This repository only contains a limited web application that serves whichever HTML is already on disk, without any additional limitations.

There is a separate project, the [cortex build system](https://github.com/dginev/CorTeX/), which prepares the HTML, based on sources I pull from the [S3 bulk download](https://arxiv.org/help/bulk_data_s3). There is also a separate dashboard to inspect the [build results with latexml](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml), while the issues in this repository focus on individual examples in depth.

I try to update on the 6th of every month with the latest HTML files, so you should see the `2207` articles appear around August 6th.

This is in some sense a temporary state of affairs - the final solution will integrate the HTML previews with the main submission process of arXiv itself, and make them available alongside the main paper PDF. That work is likely to happen somewhere under the [arxiv organization on github](https://github.com/arxiv).

Note that ar5iv is the only project that relies on the S3 bucket, rather than pull from the live arXiv site. I expect to have some conversations with the arXiv team shortly after summer to see what is the easiest way to improve the situation, but it will likely remain like this until the end of 2022.

**Comment by CreatorZZY** [comment]
Thanks.
