### ISSUE TITLE
javascript bookmarklet

### ISSUE THREAD

**Issue by yuxiliu1995** [dginev/ar5iv#240]
I wrote a javascript bookmarklet useful for opening ar5iv. I actually don't use bookmarklet, but use the javascript directly mapped to a shortkey.

```javascript
var url = window.location.href
let result = url.replace(/arxiv/g, "ar5iv");
var win = window.open(result, '_self');
win.focus();
```

```javascript
javascript:(function()%7Bvar%20url%20%3D%20window.location.href%0Alet%20result%20%3D%20url.replace(%2Farxiv%2Fg%2C%20%22ar5iv%22)%3B%0Avar%20win%20%3D%20window.open(result%2C%20'_self')%3B%0Awin.focus()%3B%7D)()%3B
```

```html
<a href="javascript:(function()%7Bvar%20url%20%3D%20window.location.href%0Alet%20result%20%3D%20url.replace(%2Farxiv%2Fg%2C%20%22ar5iv%22)%3B%0Avar%20win%20%3D%20window.open(result%2C%20'_self')%3B%0Awin.focus()%3B%7D)()%3B">bookmarklet</a>
```

**Comment by dginev** [comment]
Thanks for sharing @yuxiliu1995 !

But maybe you/others reading here can also use one of the bookmarklets posted to the browser extension stores?

For example:
- [arxiv -> ar5iv, Chrome](https://chrome.google.com/webstore/detail/arxiv-%3E-ar5iv/ledhlnbblmkmfdckpmolbpocibcanfda)
- [withAr5iv, Chrome](https://chrome.google.com/webstore/detail/withar5iv/pcboocjafhilbgocjcnlcoilacnmncam)
- [withAr5iv, Apple app store](https://apps.apple.com/us/app/with-ar5iv-arxiv/id1610822864)

I think we don't have a published one for Firefox yet - so that could be one target to create a new extension.

I will close here, since I don't think there is any action possible from within ar5iv itself, but hopefully the issue will be a good signpost for others to find directions. I think we also had #109 touching on the extension question - maybe I should add a new label.
