### ISSUE TITLE
Improve article 2108.07232 (\@footnotemark)

### ISSUE THREAD

**Issue by jowens** [dginev/ar5iv#261]
**Exact location of issue**
Right before "II-AHigh-Level GPU Cuckoo Hashing Implementation Strategy".
https://ar5iv.labs.arxiv.org/html/2108.07232

**Problem details**

The LaTeX command `\@footnotemark` is not supported (no footnote appears).
http://latexref.xyz/_005cfootnotemark.html

**Desktop**
MacOS, Chrome

<img width="326" alt="Cursor_and__2108_07232__Better_GPU_Hash_Tables" src="https://user-images.githubusercontent.com/976970/196055861-2a6166d8-3b68-4764-b788-cd5cf656f1e5.png">

**Comment by dginev** [comment]
Hey @jowens - I will merge the 3 issues you opened into one, despite them outlining 3 separate problems. No action needed on your part, just letting you know.

I am trying to organize the issues here as "one per article", since just opening that for each problematic case in arXiv will lead to >50,000 issues.
