### ISSUE TITLE
Improve article 1103.4507: \today should be date of submission perhaps

### ISSUE THREAD

**Issue by darijgr** [dginev/ar5iv#395]
The date in [arXiv:1103.4507](https://ar5iv.labs.arxiv.org/html/1103.4507) has a `\today` in it, which appears to be getting compiled to an empty string. Shouldn't it be compiled to the date of submission?

**Comment by dginev** [comment]
Thank you for the report! This enhancement is beyond the current scope of ar5iv as a project.

It *may* be better-handled in a future where arXiv itself builds the HTML pages - a first version of which is coming by the end of the year. 

The technical problem is that the submission date is completely external to the TeX source bundles - so it requires a custom build process to 1) obtain the metadata from arXiv OAI and then 2) override `\today` via some latexml mechanism. It is possible, but it is much easier from within, as arXiv can leverage their DB information directly.

Let me add that I believe this is currently also unsolved in arXiv's PDF workflow - `\today` will represent the build date of the PDF, rather than the submission date of the article. 

I suspect it is generally better for authors to use a fixed date in such cases, and avoid the `\today` macro.

Closing here, but I am bookkeeping the issue in the "arXiv integration" milestone, so it is easy to find in the future.

**Comment by darijgr** [comment]
Oh yes, I agree the arXiv should fix this on their end.

I try to get rid of \today whenever I post on the arXiv, but sometimes I forget, and so do many other authors.
