### ISSUE TITLE
Improve article 2109.02101: Version number gets ignored

### ISSUE THREAD

**Issue by darijgr** [dginev/ar5iv#398]
The URL [https://ar5iv.labs.arxiv.org/html/2109.02101v3](https://ar5iv.labs.arxiv.org/html/2109.02101v3) should lead to version 3 of the article, right? Apparently it leads to v1 or v2.

Likewise, I think [https://ar5iv.labs.arxiv.org/html/2109.02101](https://ar5iv.labs.arxiv.org/html/2109.02101) should also default to the newest version.

**Comment by darijgr** [comment]
I'm not sure this is a good state to keep in. Why default to v1 instead of the latest?

**Comment by dginev** [comment]
> Why default to v1 instead of the latest?

It's not even v1 I'm afraid. The current ar5iv is seeded by the [bulk sources](https://info.arxiv.org/help/bulk_data.html) from arXiv, and then *updated* at irregular intervals to the latest version of an article. The last update was in August 2023, however the last full rebuild of ar5iv was last December. We intend to do another full rebuild by the end of the year, and also update alongside.

But because the update is a custom step I have to execute, I can't guarantee that all articles will have the latest version displayed.

> I'm not sure this is a good state to keep in.

I agree. ar5iv is meant to be sunset as soon as the native arXiv HTML stabilizes, and will start redirecting to the official pages, where versioned links will resolve correctly. The current ar5iv is very much a temporary state. But all github issues that touch on conversion flaws are very much appreciated - and will not get lost.

**Comment by darijgr** [comment]
Aaah, that's better than v1; at least it doesn't regurgitate the really old stuff this way. Understand; I thought it would pull updates from the arXiv.
