### ISSUE TITLE
Improve article 2303.15343

### ISSUE THREAD

**Issue by fluke8** [dginev/ar5iv#510]
**Problem details**

 - Conversion to HTML had a Fatal error and exited abruptly. This document may be truncated or damaged.

**Desktop (please complete the following information)**
 - OS: Windows 10
 - Browser: Yandex Browser

**(Optional) Screenshots**
![image](https://github.com/user-attachments/assets/625a2ec5-c957-422c-ad88-0a3ceea29e6c)

**Comment by dginev** [comment]
Thank you for the report!

Sadly, the latest version of that paper has retracted the TeX source, and left only the PDF version on arXiv, as visible here:
https://arxiv.org/abs/2303.15343

Due to this, ar5iv doesn't have a usable source to convert to HTML, and we won't be able to include this article. Feel free to contact the authors about publishing a new version to arXiv with the source included, so that an HTML conversion can at least be attempted.

**Comment by fluke8** [comment]
can you use the old version of this article to display on the ar5iv with a note that this is the old version?

**Comment by dginev** [comment]
One could, but it is out of scope for the current stage of the project. 

I am working on making these available in the main arXiv site next, and planning to retire ar5iv soon after.

**Comment by fluke8** [comment]
ok, thank you
