### ISSUE TITLE
"Math input error", improve math/0601063

### ISSUE THREAD

**Issue by Vbansal21** [dginev/ar5iv#64]
This is a great conversion of the PDFs to html5 web pages, but there are a lot of math input errors in documents presented here on ar5iv website, in this article and others.

**Comment by dginev** [comment]
Hi @Vbansal21 , the way you framed the issue did not have an article id - could you use the "report an issue" button at the bottom of an article and follow the template?

It would be quite important to know both the document you're looking at, the specific formulas, and the operating system + browser that you are using. Then I can move to resolve the errors.

Thank you!

**Comment by Vbansal21** [comment]
Actually I was just exploring your work, and came across the issue during random viewing different papers by clicking 'feeling lucky' button 😅, such as https://ar5iv.org/html/math/0601063 , https://ar5iv.org/html/hep-th/0601099 etc.
I am viewing it on Android: google chrome (desktop site enabled and disabled).

Though great work!!!

**Comment by dginev** [comment]
Perfect, I'm attaching a screenshot:

![image](https://user-images.githubusercontent.com/348975/153753292-a45cdf86-dfac-497a-86b3-ef5cc2ba6d8d.png)

I tend to view the site on Firefox, where MathML is rendered natively and this type of error doesn't exist, which is why it's very helpful to be given the article links directly - I appreciate it.

While some of these are limitation of the polyfill rendering the math on Chrome, others may be flaws in the way we generate the formulas.

Feel free to try firefox out if you'd like to avoid the issue already today. But hopefully we find a path to make all formulas viewable in all browsers.

**Comment by Vbansal21** [comment]
Closing issue. As far as I have opened different articles, they have been displaying fine.
