### ISSUE TITLE
UTF characters not accepted? Improve article 2105.07028

### ISSUE THREAD

**Issue by mr-c** [dginev/ar5iv#9]
**Exact location of issue**

https://ar5iv.org/html/2105.07028#bib.bib2

Also the authors list at the top, `HervÃ© MÃ©nager` should be `Hervé Ménager`

**Desktop (please complete the following information)**
 - OS: Debian Testing
 - Browser: Firefox 91.5.0esr (64-bit)

Thanks for the great service!

**Comment by dginev** [comment]
Thanks @mr-c ! This is an embarrassing double-encoding glitch which should be rather easy to eliminate.

**Comment by marshalmiller** [comment]
Hey @dginev,
I'd like to help with this project. Could I take up this issue?

**Comment by dginev** [comment]
Hi @marshalmiller ! I decided to take a look if it's really easy so that I say "yes" to your request!
You should only need a [recent latexml](https://github.com/brucemiller/LaTeXML) installed to try and diagnoze specific problems.

Here is what I did, which you can reuse on other issues:
```
$ wget https://ar5iv.org/source/2105.07028.zip
$ latexmlc 2105.07028.zip --dest=test.html \
      --preload=[ids,nobibtex,localrawstyles]latexml.sty \
      --nodefaultresources \
      --css=https://cdn.jsdelivr.net/gh/dginev/ar5iv-css@0.7.2/css/ar5iv.min.css
```

If you convert using only these options, you realize _wait_ the encoding problem isn't there. At which point this issue switches from "easy" to a "medium" label, as the underlying problem is in a setting we use due to legacy arXiv, namely:
```
--inputencoding='iso-8859-1'
```

Here are the [exact options](https://github.com/dginev/LaTeXML-Plugin-Cortex/blob/master/bin/latexml_worker#L278-L294) which the latexml workers use when they pass over each arXiv article. 

For most errors where latexml lacks coverage, or has fidelity mistakes, the options are not that important, as you'll see the issue any which way you decide to convert. But with this double-encoding problem, the situation is a bit more tricky -- and I'll need to do a deep dive to see exactly why, as I do recall testing other UTF-8 with this `--inputencoding` set.

You can try tinkering from here, or take this step-by-step description of what I did to triage any of the other issues. You should expect to hit various walls where the errors look impenetrable, or documentation is lacking, or the implementation of latexml looks impenetrable, at which point you're welcome to just share a comment of what you did and where you stopped. Thanks!

**Comment by dginev** [comment]
Hi @mr-c ,

If you'd like, please take a look at the latest rendering of
 https://ar5iv.org/html/2105.07028

I've decided to err on the site of more recent articles, now that the showcase is public, and the input encoding I mentioned above. We'll need to stay on guard for old articles encountering issues, but at least we won't cause active harm to the newer sets.

**Comment by mr-c** [comment]
Thank you very much @dginev !
